# Generated by Django 4.2.17 on 2025-05-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "inn",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("balance", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("operation_id", models.UUIDField(primary_key=True, serialize=False)),
                ("amount", models.PositiveIntegerField()),
                ("payer_inn", models.CharField(max_length=12)),
                ("document_number", models.CharField(max_length=50)),
                ("document_date", models.DateTimeField()),
            ],
        ),
    ]
