# Generated by Django 4.2.17 on 2025-05-29 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "inn",
                    models.CharField(
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(\\d{10}|\\d{12})$",
                                message="ИНН должен содержать 10 или 12 цифр.",
                            )
                        ],
                    ),
                ),
                ("balance", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("operation_id", models.UUIDField(primary_key=True, serialize=False)),
                ("amount", models.PositiveIntegerField()),
                ("payer_inn", models.CharField(max_length=12)),
                ("document_number", models.CharField(max_length=50)),
                ("document_date", models.DateTimeField()),
            ],
        ),
    ]
